### ISSUE TITLE
leaves fall intermittently

### ISSUE THREAD

**Issue by Jukabofy** [OrderedChaos-Dev/Pioneer#1]
I can see this woth blossom and savanna trees

**Comment by OrderedChaos-Dev** [comment]
Hi, sorry I missed this. It's been 2 years but the answer to this is the leaves are decaying because they're generating too far from the log. And it's doing that because sometimes trees generate large enough that it causes that, which is a side effect of re-using some vanilla methods to place leaves, but considering it's been 2 years I'll close this but will put in effort to resolve this in later versions
