### ISSUE TITLE
Crash MC 1.19.2

### ISSUE THREAD

**Issue by OysterStew** [OrderedChaos-Dev/Pioneer#3]
Pioneer is causing latest Blueprint mod to crash.

[Crash Log](https://github.com/OrderedChaos-Dev/Pioneer/files/13532679/crash-2023-12-01_18.41.09-server.txt)

[Mod List](https://github.com/OrderedChaos-Dev/Pioneer/files/13532698/modlist.txt)

**Comment by OrderedChaos-Dev** [comment]
This is caused by incompatibilities between biome mods due to the way Minecraft places features. I personally have Pioneer, Autumnity, Environmental, Atmospheric, and BoP but haven't had any issues  
Unfortunately I'm away for the next couple of weeks with no access to my computer so I'll have to wait until I'm back home to fix this

**Comment by OysterStew** [comment]
Thanks. Take your time and have fun :)

**Comment by OrderedChaos-Dev** [comment]
Hi, very sorry I never got back to this. I remember this being a feature order cycle issue, which unfortunately is an annoying part of handling world generation in biomes.
In the latest update (though on 1.20.1), I've tried to write it in a way to avoid this sort of error when interacting with other biome mods.
