### ISSUE TITLE
Feature order crash MC 1.20.1

### ISSUE THREAD

**Issue by OysterStew** [OrderedChaos-Dev/Pioneer#4]
This again using Forge 47.3.10

https://file.io/fszqNUP73IiB

**Comment by OrderedChaos-Dev** [comment]
The link says the file was deleted

**Comment by OysterStew** [comment]
[crash-2024-10-22_10.36.03-client.txt](https://github.com/user-attachments/files/17492985/crash-2024-10-22_10.36.03-client.txt)

**Comment by OrderedChaos-Dev** [comment]
For these feature order issues, it's pretty much just an incompatibility with biome mods, due to the rules in how they're configured. The way to solve this is a datapack targeting either this mod or the other mod and sync how the offending biome lists its features. I can give more detailed instructions if you'd like.

**Comment by OysterStew** [comment]
Found this and it works  https://legacy.curseforge.com/minecraft/mc-mods/feature-recycler

**Comment by OrderedChaos-Dev** [comment]
Nice, glad you got it figured out
